-- ═══════════════════════════════════════════════════════════════
-- SEED DATA: 8 Produk Katalog euphoric.disorder
-- Jalankan SQL ini di Supabase SQL Editor setelah 001_create_admin_tables.sql
-- Project: aaiaochlzcaltkjbawqh
-- ═══════════════════════════════════════════════════════════════

INSERT INTO products (
  slug,
  subject,
  case_id,
  name,
  tagline,
  material,
  price_idr,
  original_price_idr,
  status,
  filed_under,
  description,
  story,
  fabric_gsm,
  fabric_composition,
  fabric_feel,
  fit_silhouette,
  print_technique,
  print_location,
  image_front,
  image_back,
  image_details,
  image_lookbook,
  colors,
  sizes_available,
  size_chart,
  care_instructions,
  batch_info,
  model_info,
  shopee_url,
  sort_order,
  is_published
) VALUES
(
  'candy-hoodie-ed',
  '001',
  'ED-CASE-001',
  'Candy Hoodie ED',
  'Manis di permukaan, racun di dalam.',
  'Cotton Fleece Premium 330 GSM',
  350000,
  420000,
  'LIMITED',
  ARRAY['Candy', 'Limited', 'Hoodie'],
  'Subject 001. Hoodie fleece 330 GSM edisi terbatas. Pola all-over pill/candy yang membedah ilusi kenikmatan instan dan adiksi modern.',
  'Subject 001 merupakan manifesto visual pertama Euphoric Disorder. Mengambil metafora butiran permen berwarna-warni yang tampak menggoda di kejauhan, namun ketika diamati secara forensik, tiap butir merupakan kapsul kimia sintetis. Ini adalah sindiran terhadap adiksi modern—di mana masyarakat menenggak ilusi manis untuk melupakan kekacauan realitas. Diproduksi dengan bahan katun fleece seberat 330 GSM berstruktur tebal dengan pola drop-shoulder yang tegap di badan.',
  330,
  '80% Cotton Fleece, 20% Polyester Anti-Shrink',
  'Tebal berbobot, bagian dalam brushed fleece lembut dan hangat.',
  'Boxy Relaxed Drop-Shoulder Hoodie',
  'All-Over Digital Reactive High-Definition Print',
  ARRAY['Seluruh Badan & Lengan (All-Over)', 'Hood Lining'],
  '/img/products/candy-hoodie.png',
  NULL,
  ARRAY['/img/products/candy-hoodie.png'],
  ARRAY[]::TEXT[],
  '[{"name": "Charcoal Black Base", "hex": "#1A1A1A"}, {"name": "Cream White Base", "hex": "#F3EFE0"}]'::jsonb,
  ARRAY['S', 'M', 'L', 'XL', 'XXL'],
  '[{"size": "S", "chest": 56, "length": 68, "sleeve": 60}, {"size": "M", "chest": 59, "length": 71, "sleeve": 62}, {"size": "L", "chest": 62, "length": 74, "sleeve": 64}, {"size": "XL", "chest": 65, "length": 77, "sleeve": 66}, {"size": "XXL", "chest": 68, "length": 79, "sleeve": 67}]'::jsonb,
  ARRAY[
    'Cuci menggunakan air dingin (suhu ruang) dengan deterjen lembut.',
    'Balik pakaian (inside-out) saat mencuci dan menjemur agar pigmen sablon awet.',
    'Hindari penggunaan pemutih berbahan klorin keras.',
    'Jangan menyetrika langsung pada permukaan sablon — setrika dari sisi dalam dengan suhu sedang.',
    'Keringkan dengan cara diangin-anginkan alami, hindari mesin pengering berputar tinggi.'
  ],
  'Batch 01 — Limited Run (50 Pieces Only)',
  'Model pria 178 cm / 72 kg mengenakan Size L',
  'https://shopee.co.id/compaxgrup',
  1,
  true
),
(
  'warondrugs-m3',
  '003',
  'ED-CASE-003',
  'Kaos #WarOnDrugs — M3',
  'Sebuah pengamatan empiris, bukan perayaan.',
  'Cotton Combed 24s',
  145000,
  175000,
  'OPEN',
  ARRAY['War on Drugs', 'T-Shirt'],
  'Subject 003. Katun combed 24s bersablon plastisol micro-cured. Pembuka seri ikonik #WarOnDrugs dengan cetakan tipografi RLX.',
  'Seri #WarOnDrugs lahir dari arsip catatan kasus narkotika jalanan di ibu kota. Seri M3 menyoroti paradoks kata ''RLX'' (Relax) yang sering disalahartikan sebagai jalan pintas kimiawi. Cetakan sablon di dada kiri diperlakukan layaknya cap barang bukti laboratorium, sementara punggung mencetak kutipan reflektif ''Flying is not always in the sky''. Kami mendokumentasikan gejala sosial ini ke atas medium katun 24s yang nyaman dipakai sehari-hari.',
  185,
  '100% Ring Spun Combed Cotton',
  'Halus, adem di iklim tropis, daya serap keringat maksimal.',
  'Boxy Casual Streetwear Fit',
  'Plastisol Screen Printing with Matte Finish',
  ARRAY['Dada Kiri (Tipografi RLX)', 'Punggung Tengah (Case Artwork)'],
  '/img/products/warondrugs-m3.png',
  NULL,
  ARRAY[]::TEXT[],
  ARRAY[]::TEXT[],
  '[{"name": "Deep Pitch Black", "hex": "#121212"}]'::jsonb,
  ARRAY['S', 'M', 'L', 'XL', 'XXL'],
  '[{"size": "S", "chest": 52, "length": 69, "sleeve": 23}, {"size": "M", "chest": 55, "length": 72, "sleeve": 24}, {"size": "L", "chest": 58, "length": 75, "sleeve": 25}, {"size": "XL", "chest": 61, "length": 78, "sleeve": 26}, {"size": "XXL", "chest": 64, "length": 80, "sleeve": 27}]'::jsonb,
  ARRAY[
    'Cuci menggunakan air dingin (suhu ruang) dengan deterjen lembut.',
    'Balik pakaian (inside-out) saat mencuci dan menjemur agar pigmen sablon awet.',
    'Hindari penggunaan pemutih berbahan klorin keras.',
    'Jangan menyetrika langsung pada permukaan sablon — setrika dari sisi dalam dengan suhu sedang.',
    'Keringkan dengan cara diangin-anginkan alami, hindari mesin pengering berputar tinggi.'
  ],
  'Katalog Reguler — Ready Stock & PO Terjadwal',
  'Model pria 175 cm / 68 kg mengenakan Size M',
  'https://shopee.co.id/compaxgrup',
  2,
  true
),
(
  'warondrugs-m7-lego',
  '007',
  'ED-CASE-007',
  'Kaos #WarOnDrugs — M7 "Lego"',
  'Dibangun dari kepingan, hancur dalam hitungan detik.',
  'Cotton Combed 24s',
  150000,
  180000,
  'OPEN',
  ARRAY['War on Drugs', 'T-Shirt'],
  'Subject 007. Seri #WarOnDrugs varian ''Lego''. Metafora kepingan kebiasaan adiktif yang tersusun balok demi balok.',
  'Subject 007 mengabstraksikan kebiasaan adiktif sebagai balok-balok mainan Lego. Sekilas terlihat kekanak-kanakan dan tidak berbahaya, namun setiap balok yang tertumpuk membangun penjara psikologis bagi korbannya. Dicetak dengan teknik sablon multi-layer plastisol untuk menghasilkan tekstur balok yang tegas dengan separasi warna tajam.',
  185,
  '100% Combed Cotton 24s',
  'Lembut, tidak menerawang, tidak kaku.',
  'Classic Boxy Oversize',
  'Manual Multi-Pass Plastisol Ink',
  ARRAY['Dada Depan Penuh (Graphic Lego)', 'Lengan Kanan (Emblem Seri)'],
  '/img/products/warondrugs-m7.png',
  NULL,
  ARRAY[]::TEXT[],
  ARRAY[]::TEXT[],
  '[{"name": "Carbon Black", "hex": "#171717"}]'::jsonb,
  ARRAY['S', 'M', 'L', 'XL', 'XXL'],
  '[{"size": "S", "chest": 52, "length": 69, "sleeve": 23}, {"size": "M", "chest": 55, "length": 72, "sleeve": 24}, {"size": "L", "chest": 58, "length": 75, "sleeve": 25}, {"size": "XL", "chest": 61, "length": 78, "sleeve": 26}, {"size": "XXL", "chest": 64, "length": 80, "sleeve": 27}]'::jsonb,
  ARRAY[
    'Cuci menggunakan air dingin (suhu ruang) dengan deterjen lembut.',
    'Balik pakaian (inside-out) saat mencuci dan menjemur agar pigmen sablon awet.',
    'Hindari penggunaan pemutih berbahan klorin keras.',
    'Jangan menyetrika langsung pada permukaan sablon — setrika dari sisi dalam dengan suhu sedang.',
    'Keringkan dengan cara diangin-anginkan alami, hindari mesin pengering berputar tinggi.'
  ],
  'Arsip Berkas Perkara 2023',
  'Model 180 cm / 75 kg mengenakan Size L',
  'https://shopee.co.id/compaxgrup',
  3,
  true
),
(
  'warondrugs-m8',
  '008',
  'ED-CASE-008',
  'Kaos #WarOnDrugs — M8',
  'Kajian dingin yang dipakai tepat di dada.',
  'Cotton Combed 24s',
  145000,
  NULL,
  'OPEN',
  ARRAY['War on Drugs', 'T-Shirt'],
  'Subject 008. Potret grafis investigasi forensik terhadap distribusi substansi terlarang di lanskap urban.',
  'Subject 008 menghadirkan estetika dokumen berkas perkara rahasia. Menggunakan komposisi tipografi bergaya stempel forensik dan koordinat peta TKP. Desain ini mengajak pemakainya untuk tidak bersikap naif terhadap realitas jalanan kota metropolitan.',
  185,
  '100% Cotton Combed 24s Premium',
  'Sejuk dan tahan lama meski dicuci berulang.',
  'Drop-Shoulder Boxy Fit',
  'Plastisol Ink dengan Finishing Doff',
  ARRAY['Dada Tengah (Case File Emblem)'],
  '/img/products/warondrugs-m8.png',
  NULL,
  ARRAY[]::TEXT[],
  ARRAY[]::TEXT[],
  '[{"name": "Washed Black", "hex": "#1C1C1C"}]'::jsonb,
  ARRAY['S', 'M', 'L', 'XL', 'XXL'],
  '[{"size": "S", "chest": 52, "length": 69, "sleeve": 23}, {"size": "M", "chest": 55, "length": 72, "sleeve": 24}, {"size": "L", "chest": 58, "length": 75, "sleeve": 25}, {"size": "XL", "chest": 61, "length": 78, "sleeve": 26}, {"size": "XXL", "chest": 64, "length": 80, "sleeve": 27}]'::jsonb,
  ARRAY[
    'Cuci menggunakan air dingin (suhu ruang) dengan deterjen lembut.',
    'Balik pakaian (inside-out) saat mencuci dan menjemur agar pigmen sablon awet.',
    'Hindari penggunaan pemutih berbahan klorin keras.',
    'Jangan menyetrika langsung pada permukaan sablon — setrika dari sisi dalam dengan suhu sedang.',
    'Keringkan dengan cara diangin-anginkan alami, hindari mesin pengering berputar tinggi.'
  ],
  'Serial Drop — Stock Terbatas',
  'Model 174 cm / 65 kg mengenakan Size M',
  'https://shopee.co.id/compaxgrup',
  4,
  true
),
(
  'warondrugs-m14',
  '014',
  'ED-CASE-014',
  'Kaos #WarOnDrugs — M14',
  'Nomor besar, pertanyaan yang lebih besar.',
  'Cotton Combed 24s',
  145000,
  NULL,
  'OPEN',
  ARRAY['War on Drugs', 'T-Shirt'],
  'Subject 014. Tipografi angka kasus besar bergaris tepi forensik dengan cap stempel ''EVIDENCE CONFIDENTIAL''.',
  'Subject 014 merekam skala masif dari kasus-kasus yang tak pernah benar-benar selesai. Menampilkan tipografi monolitik ''14'' yang diisi dengan barcode dan stempel merah investigasi. Dirancang untuk siluet streetwear santai dengan jahitan rantai pundak ekstra kokoh.',
  185,
  '100% Cotton Combed 24s',
  'Karakter katun murni yang menyerap keringat dengan baik.',
  'Boxy Oversized Fit',
  'Discharge & Plastisol Hybrid Print',
  ARRAY['Dada Depan', 'Tengkuk Leher'],
  '/img/products/warondrugs-m14.png',
  NULL,
  ARRAY[]::TEXT[],
  ARRAY[]::TEXT[],
  '[{"name": "Deep Black", "hex": "#111111"}]'::jsonb,
  ARRAY['S', 'M', 'L', 'XL', 'XXL'],
  '[{"size": "S", "chest": 52, "length": 69, "sleeve": 23}, {"size": "M", "chest": 55, "length": 72, "sleeve": 24}, {"size": "L", "chest": 58, "length": 75, "sleeve": 25}, {"size": "XL", "chest": 61, "length": 78, "sleeve": 26}, {"size": "XXL", "chest": 64, "length": 80, "sleeve": 27}]'::jsonb,
  ARRAY[
    'Cuci menggunakan air dingin (suhu ruang) dengan deterjen lembut.',
    'Balik pakaian (inside-out) saat mencuci dan menjemur agar pigmen sablon awet.',
    'Hindari penggunaan pemutih berbahan klorin keras.',
    'Jangan menyetrika langsung pada permukaan sablon — setrika dari sisi dalam dengan suhu sedang.',
    'Keringkan dengan cara diangin-anginkan alami, hindari mesin pengering berputar tinggi.'
  ],
  'Serial Drop — Ready Stock',
  'Model 177 cm / 70 kg mengenakan Size L',
  'https://shopee.co.id/compaxgrup',
  5,
  true
),
(
  'warondrugs-s4',
  'S4',
  'ED-CASE-S04',
  'Kaos #WarOnDrugs — S4',
  'Bukti yang bisa dibalik, dua sudut pandang perkara.',
  'Cotton Combed 24s',
  155000,
  185000,
  'OPEN',
  ARRAY['War on Drugs', 'T-Shirt', 'Limited'],
  'Subject S4. Rilisan dua sisi (depan & belakang) yang menarasikan kronologi penangkapan dan bukti laboratoris.',
  'Subject S4 adalah salah satu berkas paling detail dalam arsip Euphoric Disorder. Bagian depan mencatat kode perkara forensik, sedangkan bagian belakang memuat cetakan visual berukuran penuh yang menguraikan diagram kronologi kejadian. Seperti semua bukti yang sah di mata hukum, pakaian ini menuntut untuk diamati dari dua sisi yang berbeda.',
  190,
  '100% Combed Cotton 24s Heavy Treatment',
  'Permukaan halus, gramasi tegap, tidak mudah kusut.',
  'Streetwear Boxy Fit — Drop Shoulder',
  'Dual-Sided High Density Plastisol',
  ARRAY['Dada Depan (Logo Berkas)', 'Punggung Penuh (Diagram Kasus S4)'],
  '/img/products/warondrugs-s4.png',
  '/img/products/warondrugs-s4b.png',
  ARRAY['/img/products/warondrugs-s4.png', '/img/products/warondrugs-s4b.png'],
  ARRAY[]::TEXT[],
  '[{"name": "Black Charcoal", "hex": "#141414"}]'::jsonb,
  ARRAY['S', 'M', 'L', 'XL', 'XXL'],
  '[{"size": "S", "chest": 52, "length": 69, "sleeve": 23}, {"size": "M", "chest": 55, "length": 72, "sleeve": 24}, {"size": "L", "chest": 58, "length": 75, "sleeve": 25}, {"size": "XL", "chest": 61, "length": 78, "sleeve": 26}, {"size": "XXL", "chest": 64, "length": 80, "sleeve": 27}]'::jsonb,
  ARRAY[
    'Cuci menggunakan air dingin (suhu ruang) dengan deterjen lembut.',
    'Balik pakaian (inside-out) saat mencuci dan menjemur agar pigmen sablon awet.',
    'Hindari penggunaan pemutih berbahan klorin keras.',
    'Jangan menyetrika langsung pada permukaan sablon — setrika dari sisi dalam dengan suhu sedang.',
    'Keringkan dengan cara diangin-anginkan alami, hindari mesin pengering berputar tinggi.'
  ],
  'Edisi Khusus Dua Sisi',
  'Model 178 cm / 72 kg mengenakan Size L',
  'https://shopee.co.id/compaxgrup',
  6,
  true
),
(
  'custom-sablon-batch',
  '009',
  'ED-SERV-009',
  'Custom Sablon & Apparel — Batch Production',
  'Konveksi & sablon berstandar distro untuk komunitas dan brand Anda.',
  'Combed 24s / 16s Heavyweight / Fleece 330gsm',
  55000,
  65000,
  'OPEN',
  ARRAY['Custom Sablon', 'Service'],
  'Subject 009. Layanan pembuatan kaos & apparel kustom skala komunitas atau brand kolektif (min. 12 pcs). Pilihan bahan Combed 24s, 16s Heavyweight (235 GSM), hingga Fleece 330gsm dengan sablon Plastisol / Discharge.',
  'Euphoric Disorder tidak hanya merilis artikel koleksi sendiri, tetapi juga membuka fasilitas produksi untuk brand independen, komunitas otomotif/musik, dan instansi kreatif. Kami memastikan standar bahan katun combed terbaik (dari 24s standar harian hingga 16s Heavyweight 235 GSM berpola boxy), jahitan rantai tiga jarum, serta racikan tinta sablon tahan cuci berstandar ekspor.',
  235,
  'Pilihan: Combed 24s (180 GSM), 16s Heavy (235 GSM), Fleece (330 GSM)',
  'Dapat disesuaikan dengan kebutuhan proyek Anda.',
  'Pilihan: Regular Fit, Boxy Cut, Oversized Drop-Shoulder',
  'Plastisol Manual, Discharge Cabut Warna, HD 3D Rubber, atau DTF Digital',
  ARRAY['Dada', 'Punggung', 'Lengan Kiri/Kanan', 'Label Kerah Kustom'],
  '/img/shirt-gray.png',
  '/img/shirt-green.png',
  ARRAY['/img/shirt-gray.png', '/img/shirt-green.png'],
  ARRAY[]::TEXT[],
  '[{"name": "Hitam Pekat", "hex": "#111111"}, {"name": "Putih Tulang / Bone", "hex": "#EDEBDD"}, {"name": "Forest Green", "hex": "#2C3221"}, {"name": "Custom Panton Color", "hex": "#7A7A7A"}]'::jsonb,
  ARRAY['S', 'M', 'L', 'XL', 'XXL', 'XXXL'],
  '[{"size": "S", "chest": 52, "length": 69, "sleeve": 23}, {"size": "M", "chest": 55, "length": 72, "sleeve": 24}, {"size": "L", "chest": 58, "length": 75, "sleeve": 25}, {"size": "XL", "chest": 61, "length": 78, "sleeve": 26}, {"size": "XXL", "chest": 64, "length": 80, "sleeve": 27}]'::jsonb,
  ARRAY[
    'Cuci menggunakan air dingin (suhu ruang) dengan deterjen lembut.',
    'Balik pakaian (inside-out) saat mencuci dan menjemur agar pigmen sablon awet.',
    'Hindari penggunaan pemutih berbahan klorin keras.',
    'Jangan menyetrika langsung pada permukaan sablon — setrika dari sisi dalam dengan suhu sedang.',
    'Keringkan dengan cara diangin-anginkan alami, hindari mesin pengering berputar tinggi.'
  ],
  'Minimum Pemesanan: 12 pcs / Batch (Pengerjaan 7-14 hari kerja)',
  'Sampel dapat dibuat terlebih dahulu sebelum produksi massal',
  'https://shopee.co.id/compaxgrup',
  7,
  true
),
(
  'custom-sablon-satuan',
  '010',
  'ED-SERV-010',
  'Custom Sablon Satuan & Sample Build',
  'Realisasikan 1 potong desain impian Anda tanpa batasan minimum.',
  'Cotton Combed 24s / 30s',
  75000,
  90000,
  'OPEN',
  ARRAY['Custom Sablon', 'Service'],
  'Subject 010. Cetak sampel produk atau kaos custom satuan tanpa minimal order (1 pcs pun dilayani). Menggunakan cetak DTF presisi tinggi / Plastisol HD dengan detail warna tajam.',
  'Bagi Anda yang membutuhkan sampel purwarupa (prototype) sebelum produksi massal, hadiah personal, atau kaos rilisan khusus 1 of 1, layanan Subject 010 dirancang untuk Anda. Tanpa minimal order, kami memproses desain Anda menggunakan cetak digital Direct-to-Film (DTF) resolusi tinggi yang merekat kuat pada serat katun 24s murni.',
  185,
  '100% Cotton Combed 24s Soft-Treated',
  'Nyaman, adem, dan menyerap keringat.',
  'Standard & Boxy Fit',
  'Direct Transfer Film (DTF) HD & High Precision Curing',
  ARRAY['Area Cetak A3 / A4 Bebas (Depan & Belakang)'],
  '/img/hero-tee.png',
  NULL,
  ARRAY['/img/hero-tee.png'],
  ARRAY[]::TEXT[],
  '[{"name": "Solid Black", "hex": "#151515"}, {"name": "Pure White", "hex": "#FFFFFF"}]'::jsonb,
  ARRAY['S', 'M', 'L', 'XL', 'XXL'],
  '[{"size": "S", "chest": 52, "length": 69, "sleeve": 23}, {"size": "M", "chest": 55, "length": 72, "sleeve": 24}, {"size": "L", "chest": 58, "length": 75, "sleeve": 25}, {"size": "XL", "chest": 61, "length": 78, "sleeve": 26}, {"size": "XXL", "chest": 64, "length": 80, "sleeve": 27}]'::jsonb,
  ARRAY[
    'Cuci menggunakan air dingin (suhu ruang) dengan deterjen lembut.',
    'Balik pakaian (inside-out) saat mencuci dan menjemur agar pigmen sablon awet.',
    'Hindari penggunaan pemutih berbahan klorin keras.',
    'Jangan menyetrika langsung pada permukaan sablon — setrika dari sisi dalam dengan suhu sedang.',
    'Keringkan dengan cara diangin-anginkan alami, hindari mesin pengering berputar tinggi.'
  ],
  'Satuan (1-11 pcs) — Proses Cepat 2-4 Hari',
  'Cocok untuk tes desain dan sampel portofolio',
  'https://shopee.co.id/compaxgrup',
  8,
  true
)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  tagline = EXCLUDED.tagline,
  material = EXCLUDED.material,
  price_idr = EXCLUDED.price_idr,
  original_price_idr = EXCLUDED.original_price_idr,
  status = EXCLUDED.status,
  filed_under = EXCLUDED.filed_under,
  description = EXCLUDED.description,
  story = EXCLUDED.story,
  fabric_gsm = EXCLUDED.fabric_gsm,
  fabric_composition = EXCLUDED.fabric_composition,
  fabric_feel = EXCLUDED.fabric_feel,
  fit_silhouette = EXCLUDED.fit_silhouette,
  print_technique = EXCLUDED.print_technique,
  print_location = EXCLUDED.print_location,
  image_front = EXCLUDED.image_front,
  image_back = EXCLUDED.image_back,
  image_details = EXCLUDED.image_details,
  image_lookbook = EXCLUDED.image_lookbook,
  colors = EXCLUDED.colors,
  sizes_available = EXCLUDED.sizes_available,
  size_chart = EXCLUDED.size_chart,
  care_instructions = EXCLUDED.care_instructions,
  batch_info = EXCLUDED.batch_info,
  model_info = EXCLUDED.model_info,
  shopee_url = EXCLUDED.shopee_url,
  sort_order = EXCLUDED.sort_order,
  is_published = EXCLUDED.is_published;
